Select 
    TO_CHAR(TO_DATE(DATE_KEY, 'YYYYMMDD'), 'YYYY-MM-DD') as DATE_KEY,
    UPPER(CATEGORY) as TABLE_NAME, 
    UPPER(DESCRIPTION) as CHECK_NAME, 
    PRIORITY,
    DATA_SOURCE,
    TABLE_SCHEMA,
    CASE WHEN TOTAL_DISCREPANCIES=0 THEN 0 
         WHEN TOTAL_DISCREPANCIES>5 THEN 1
         ELSE 2 
    END AS STATUS
FROM ADMIN.DATA_VALIDATIONS
WHERE DATE_KEY=CURRENT_DATE();
