WITH CTE as (
SELECT TO_CHAR(TO_DATE(DATE_KEY, 'YYYYMMDD'), 'YYYY-MM-DD') as DATE_KEY,
        COUNT_IF(TOTAL_DISCREPANCIES=0) as PASS_COUNT,
        COUNT_IF(TOTAL_DISCREPANCIES>5) as FAIL_COUNT,
        COUNT_IF(TOTAL_DISCREPANCIES BETWEEN 0 AND 5) as WARN_COUNT
FROM ADMIN.DATA_VALIDATIONS)
SELECT *
  FROM CTE
    UNPIVOT(COUNT FOR STATUS IN (PASS_COUNT, FAIL_COUNT, WARN_COUNT));